exobase/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout, LoginView, PasswordChangeView
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/edit/$', views.profile_edit, name='profile_edit'),
    url(r'^profile/auth/edit/$', views.auth_edit, name='auth_edit'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.exercice_tag_list, name='post_list_by_tag'),
    url(r'^taglist/(?P<tag_slug>[-\w]+)$', views.exercice_tag_list, name='exo_list'),
    url(r'^list/$', views.ExerciceList.as_view(), name='exo_list2'),
    url(r'^exercice/(?P<exercice_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^exercice/(?P<pk>[0-9]+)/edit/$', views.ex_edit, name='post_edit'),
    url(r'^exercice/(?P<pk>[0-9]+)/enonce_edit/$', views.ex_enonce_edit, name='ex_enonce_edit'),
    url(r'^exercice/(?P<pk>[0-9]+)/addperm/$', views.ex_add_perm, name='ex_add_perm'),
    url(r'^exercice/(?P<exercice_id>[0-9]+)/addreader/$', views.ex_add_reader, name='ex_add_reader'),
    url(r'^exercice/(?P<exercice_id>[0-9]+)/addgroup/$', views.ex_add_group, name='ex_add_group'),
    url(r'^exercice/(?P<exercice_id>[0-9]+)/deletereader/$', views.ex_delete_reader, name='ex_delete_reader'),
    url(r'^exercice/(?P<exercice_id>[0-9]+)/deletegroup/$', views.ex_delete_group, name='ex_delete_group'),
    url(r'^exercice/(?P<exercice_id>[0-9]+)/solution/add/$', views.exercice_add_solution, name='exercice_add_solution'),
    url(r'^solution/(?P<pk>[0-9]+)/edit/$', views.solution_edit, name='solution_edit'),
    url(r'^solution/(?P<pk>[0-9]+)/$', views.solution_detail, name='solution_detail'),
    url(r'^solution/(?P<solution_id>[0-9]+)/addreader/$', views.sol_add_reader, name='sol_add_reader'),
    url(r'^solution/(?P<solution_id>[0-9]+)/addgroup/$', views.sol_add_group, name='sol_add_group'),
    url(r'^solution/(?P<solution_id>[0-9]+)/deletereader/$', views.sol_delete_reader, name='sol_delete_reader'),
    url(r'^solution/(?P<solution_id>[0-9]+)/deletegroup/$', views.sol_delete_group, name='sol_delete_group'),
    url(r'^solution/(?P<pk>[0-9]+)/delete/$', views.solution_delete, name='solution_delete'),
    url(r'^exercice/(?P<exercice_id>[0-9]+)/add/$', views.exercice_add_to_folder, name='exercice_add_to_folder'),
    url(r'^folder/$', views.folder_list, name='folder_list'),
    url(r'^folder/(?P<folder_id>[0-9]+)/$', views.detail_folder, name='folder_detail'),
    url(r'^folder/(?P<folder_id>[0-9]+)/delete/$', views.folder_delete, name='folder_delete'),
    url(r'^folder/resume/(?P<folder_id>[0-9]+)/$', views.resume_folder, name='folder_resume'),
    url(r'^folder/(?P<folder_id>[0-9]+)/up/(?P<exercice_id>[0-9]+)/$', views.folder_up_exercice, name='folder_up_exercice'),
    url(r'^folder/(?P<folder_id>[0-9]+)/down/(?P<exercice_id>[0-9]+)/$', views.folder_down_exercice, name='folder_down_exercice'),    
    url(r'^folder/(?P<pk>[0-9]+)/edit/$', views.folder_edit, name='folder_edit'),
    url(r'^folder/(?P<pk>[0-9]+)/add/$', views.folder_add_exercice, name='folder_add_exercice'),
    url(r'^folder/(?P<folder_id>[0-9]+)/delete/(?P<exercice_id>[0-9]+)/$', views.delete_exercice_folder, name='delete_exercice_folder'),
    url(r'^new/$', views.ex_new, name='post_new'),
    url(r'^folder/new/$', views.folder_new, name='folder_new'),
    url(r'^class/new/$', views.classe_new, name='classe_new'),
    url(r'^class/$', views.classe_list, name='classe_list'),
    url(r'^class/(?P<pk>[0-9]+)/$', views.classe_detail, name='classe_detail'),
    url(r'^class/(?P<pk>[0-9]+)/edit/$', views.classe_edit, name='classe_edit'),
    url(r'^class/(?P<pk>[0-9]+)/addfolder/$', views.classe_add_folder, name='classe_add_folder'),
    url(r'^class/(?P<classe_id>[0-9]+)/delete/$', views.classe_delete, name='classe_delete'),
    url(r'^class/(?P<classe_id>[0-9]+)/(?P<eleve_id>[0-9]+)/delete/$', views.delete_eleve_classe, name='delete_eleve_classe'),
    url(r'^macro/(?P<pk>[0-9]+)/edit/$', views.macro_edit, name='macro_edit'),
    url(r'^macro/new/$', views.macro_new, name='macro_new'),
    url(r'^search/$', views.recherche, name='recherche'),
    url(r'^search2/$', views.recherche2, name='recherche2'),
    url(r'^newuser/$', views.user_new, name='user_new'),
    url(r'^login/$', LoginView.as_view(), name='login'),  
    url(r'^password_change/$', PasswordChangeView.as_view(), name='password_change'),   
    url(r'^logout/$', logout, {'next_page': '/exobase/login'}),  
    url(r'^register/$', views.register, name='register'),  
]

openyourmath/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^exobase/', include('exobase.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='home'),

]

exobase/models.py
from django.db import models
from taggit.managers import TaggableManager
from django.contrib.auth.models import User
from django.utils import timezone
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    WORK_TYPES = (
                  ('E','Etudiant'),
                  ('P','Professeur'),
                  ('A','Autre'),
                  )
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    organization = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    work = models.CharField(max_length=1, choices=WORK_TYPES)
    website = models.URLField(default='', blank=True)
    avatar = models.ImageField(blank=True)
    
    def __str__(self):
        return 'Profil de '+str(self.user)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

    
class MacroLatex(models.Model):
    name = models.CharField(blank=True, max_length=50)
    macro = models.TextField(blank=True)
    description = models.CharField(blank=True, max_length=50)
    def __str__(self):
        return self.name
    
class Exercice(models.Model):
    VISIBILITY_TYPES = (
            ('A','Public'),
            ('P','Personnalisé'),
                        )
    name = models.CharField(blank=True, max_length=50)
    level = models.CharField(blank=True, max_length=50)
    difficulty = models.DecimalField(max_digits=2,decimal_places=1,default=0)
    popularity = models.DecimalField(max_digits=2,decimal_places=1,default=5)
    quality = models.DecimalField(max_digits=2,decimal_places=1,default=5)
    enonce_latex = models.TextField(blank=True)
    enonce_html = models.TextField(blank=True)
    description = models.TextField(blank=True)
    indication_latex = models.TextField(blank=True)
    indication_html = models.TextField(blank=True)
    macro = models.ForeignKey(MacroLatex, on_delete=models.CASCADE, blank=True, null=True)
    image = models.ImageField(blank=True)
    figure = models.TextField(blank=True) #pour insertion d'iframe
    pub_date = models.DateTimeField('date published')
    tags = TaggableManager()
    author = models.ForeignKey(User)
    visibility = models.CharField(max_length=1, choices = VISIBILITY_TYPES, default='A')
    
    def __str__(self):
        return str(self.id)

class Solution(models.Model):
    VISIBILITY_TYPES = (
            ('A','Public'),
            ('P','Personnalisé'),
            )
    quality = models.DecimalField(max_digits=2,decimal_places=1,default=5)   
    enonce_latex = models.TextField(blank=True)
    enonce_html = models.TextField(blank=True)
    macro = models.ForeignKey(MacroLatex, on_delete=models.CASCADE, blank=True, null=True)
    pub_date = models.DateTimeField('date published')
    author = models.ForeignKey(User)
    exercice = models.ForeignKey(Exercice, on_delete=models.CASCADE)
    visibility = models.CharField(max_length=1, choices = VISIBILITY_TYPES, default='A')

    def __str__(self):
        return 'Solution de Ex' + str(self.exercice.id)
    


class Comment(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField('date published')
    author = models.ForeignKey(User)
    
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    
    def __str__(self):
        return str(self.id)

class Folder(models.Model):
    exercices = models.ManyToManyField(Exercice, related_name='in_folder', through='OrderFolder')
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    pub_date = models.DateTimeField('date published',default=timezone.now)
    author = models.ForeignKey(User)
    
    def __str__(self):
        return self.name
    
    def get_exercice(self):
        return self.exercices.order_by('link_to_folder')
    
    def count_exercice(self):
        return self.exercices.count()

class OrderFolder(models.Model):
    number = models.PositiveIntegerField()
    exercice = models.ForeignKey(Exercice, related_name='link_to_folder')
    folder = models.ForeignKey(Folder)
    
    def __str__(self):
        return str(self.number)+'-'+str(self.exercice.id)
    
class Collection(models.Model):
    folders = models.ManyToManyField(Folder)
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name

class Classe(models.Model):
    name = models.CharField(blank=True, max_length=50)
    description = models.CharField(blank=True, max_length=50)
    eleves = models.ManyToManyField(User)
    year = models.CharField(blank=True, max_length=9)
    prof = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, null=False, related_name='prof',default=3)
    professeurs = models.ManyToManyField(User, blank=False, null=False, related_name='professeurs',default=1)
    
    def __str__(self):
        return self.name
    
class Oral(models.Model):
    eleve = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, null=False)
    exercices = models.ManyToManyField(Exercice)
    note = models.PositiveIntegerField()
    commentaire = models.CharField(max_length=100)
    pub_date = models.DateTimeField('date published',default=timezone.now)
    
    def __str__(self):
        return 'oral '+str(self.id)
    
class Colle(models.Model):
    oraux = models.ManyToManyField(Oral)
    author = models.ForeignKey(User,default=3)
    pub_date = models.DateTimeField('date published',default=timezone.now)
    
    def __str__(self):
        return 'colle '+str(self.id)
    
    

exobase/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Exercice, Folder, Profile, Classe
from django.contrib.auth.forms import AuthenticationForm 
from exobase.models import Solution, MacroLatex

class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['bio','organization','birth_date','work','website',]
        labels = {'work': 'Statut'}

class ExoForm(forms.ModelForm):
    
    class Meta:
        model = Exercice
        fields = ['name',
                  'visibility',
                  'description',
                  'indication_latex',
                  'macro',
                  'tags']
        labels = {
                  'name': 'Nom de l\'exercice',
                  'visibility': 'Visibilité',
                  'description': 'Description',
                  'indication_latex': 'Indications en LaTeX',
                  'macro': 'Sélectionner un fichier de macros LaTeX',
                  'tags': 'tags',
        }

class ExoForm0(forms.ModelForm):
    
    class Meta:
        model = Exercice
        fields = ['name',
                  'visibility',
                  'description',
                  'enonce_latex',
                  'indication_latex',
                  'macro',
                  'tags']
        labels = {
                  'name': 'Nom de l\'exercice',
                  'visibility': 'Visibilité',
                  'description': 'Description',
                  'enonce_latex': 'Enoncé (en LaTeX)',
                  'indication_latex': 'Indications en LaTeX',
                  'macro': 'Sélectionner un fichier de macros LaTeX',
                  'tags': 'tags',
        }

class ExoLatexForm(forms.ModelForm):
    
    class Meta:
        model = Exercice
        fields = ['enonce_latex',
                  ]
        labels = {
                  'enonce_latex': 'Source LaTeX de l\'énoncé',
        }

class ExoSearch(forms.Form):
    my_num = forms.IntegerField(label='numéro d\'exercice', widget=forms.NumberInput(attrs={'style': 'width:15ch' }) )

class ExoSearch2(forms.Form):
    my_tag = forms.CharField(label='tag d\'exercice')

class ExerciceAddSolution(forms.ModelForm):
    
    class Meta:
        model = Solution
        fields = ['enonce_latex','visibility',]
        labels = {'enonce_latex': 'Enoncé en LaTeX','visibility': 'Visibilité',}

class MacroForm(forms.ModelForm):
    
    class Meta:
        model = MacroLatex
        fields = ['name','description','macro']

class FolderForm(forms.ModelForm):
    
    class Meta:
        model = Folder
        fields = ['name','description',]
        labels = {'name': 'Nom du dossier', 'description': 'Description',
                  }
    
class FolderAddExercice(forms.Form):
    my_exercices = forms.CharField(label='numéro d\'exercices',help_text='entrer un numéro ou une liste de numéros séparés par une virgule')

    def clean_my_exercices(self):
        data = self.cleaned_data['my_exercices']    
        data = data.replace(';',',').replace(' ',',').split(',')
        data = [int(x) for x in data]   
        return data

class ExerciceAddToFolder(forms.Form):
    my_folder = forms.IntegerField(label='numéro de dossier')

class FolderForm2(forms.Form):
    name = forms.CharField(max_length=20)
    exercices = forms.ModelMultipleChoiceField(queryset=Exercice.objects.all())

class ClassForm(forms.ModelForm):
    
    class Meta:
        model = Classe
        fields = ('name','description',)
        
class ClassAddEleve(forms.Form):
    my_eleves = forms.CharField(label='identifiants d\'eleves',help_text='entrer un login ou une liste de login séparés par une virgule')

    def clean_my_eleves(self):
        data = self.cleaned_data['my_eleves']    
        data = data.replace(';',',').replace(' ',',').split(',')
        data = [str(x) for x in data]   
        return data

class ClassAddFolder(forms.Form):
    my_folder = forms.IntegerField(label='numéro de dossier',help_text='entrer un numéro identifiant de dossier')

class ConnexionForm(forms.Form):
    username = forms.CharField(label="Nom d'utilisateur", max_length=30)
    password = forms.CharField(label="Mot de passe", widget=forms.PasswordInput)
    
class NewUser(forms.ModelForm):
    class Meta:
        model=User
        fields=('username','password',)
        
class NewUser2(forms.ModelForm):
    class Meta:
        model=User
        fields=('first_name','last_name','email');        labels={'first_name': 'Prénom','last_name': 'Nom'}

        
class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Username", max_length=30, 
                               widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'username'}))
    password = forms.CharField(label="Password", max_length=30, 
                               widget=forms.PasswordInput(attrs={'class': 'form-control', 'name': 'password'}))
    

exobase/templates/exobase/classe_edit.html
{% extends 'exobase/base.html' %}

{% block content %}
 <div class="container-fluid">
<div class="row">
        <div class="col-md-6 col-md-offset-3">
    <div class="title">Classe #{{ classe_id }}</div>
  <form method="post" novalidate>
    {% csrf_token %}
    {% include 'exobase/includes/form.html' %}
    <button type="submit" class="btn btn-success btn-block">Enregistrer les modifications de cette classe</button>
  </form>
</div>
</div>
</div>
    
{% endblock %}

exobase/templates/exobase/detail.html
{% extends 'exobase/base.html' %}

{% load exobase_extras %}

{% block macro %}
 {{ exercice.macro.macro }}
{% endblock %}

{% block title %}OYM - Exercice {{ exercice.id }} {% endblock %}


{% block content %}

<div id="mySidenav" class="sidenav">

<p>
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
</p>


<div style="padding:10px">
 Changer la visibilité :
 </div>
<div>
{% if exercice|visible_by_group:'PUBLIC' %}

 <div>
 <span class="dropdown pull-right">
<form action="{% url 'ex_add_perm' pk=exercice.id %}">
	<select name="perm_box">
		<option value='public'> Public </option>
		<option value='private'> Limité </option>
	</select>
	<input type='submit'>
</form>
</span>
</div>




{% else %}
<form action="{% url 'ex_add_perm' pk=exercice.id %}">
	<select name="perm_box">
		<option value='private'> Limité </option>
		<option value='public'> Public </option>
	</select>
	<input type='submit'>
</form>


<button class="accordion"> Lecteurs autorisés : </button>

<div class="panel2">


<div class="shortlist">
<ul id="myUL" class="myshortlist">
{% for n in reader_list %}
<li><a href="#"> {{ n }} </a></li>
{% endfor %}
</ul>
</div>

<input type="text" id="myInput" class="listsearch" onkeyup="UserSearch()" placeholder="Chercher un nom..." title="Chercher un nom">

<div style="padding:10px">
Supprimer un lecteur :

 </div>
<div class="form-group">
<form method="POST" action="{% url 'ex_delete_reader' exercice_id=exercice.id %}">{% csrf_token %}
					<input id="delete_reader_box" type="text" name="delete_reader_box"
						class="input-sm form-control" placeholder="Nom">
					<button id="search_submit" type="submit"
						class="btn btn-warning btn-sm">
						<span class="glyphicon glyphicon-remove"></span> Supprimer
					</button>
</form>
</div>

<div style="padding:10px">
Ajouter un lecteur :

 </div>
<div class="form-group">
<form method="POST" action="{% url 'ex_add_reader' exercice_id=exercice.id %}">{% csrf_token %}
					<input id="add_reader_box" type="text" name="add_reader_box"
						class="input-sm form-control" placeholder="Nom">
					<button id="search_submit" type="submit"
						class="btn btn-primary btn-sm">
						<span class="glyphicon glyphicon-plus"></span> Ajouter
					</button>
</form>
</div>
</div>

<button class="accordion"> Classes autorisées : </button>

<div class="panel2">
<div class="shortlist">
<ul id="myUL2" class="myshortlist" >
{% for n in classe_list %}
<li><a href="#"> #{{ n.0 }} {{ n.1 }} </a></li>
{% endfor %}
</ul>
</div>

<input type="text" id="myInput2" class="listsearch" onkeyup="GroupSearch()" placeholder="Chercher une classe" title="Chercher une classe">

<div style="padding:10px">
Ajouter une classe :

 </div>
<div class="form-group">
<form method="POST" action="{% url 'ex_add_group' exercice_id=exercice.id %}">{% csrf_token %}
					<input id="add_group_box" type="text" name="add_group_box"
						class="input-sm form-control" placeholder="Numéro">
					<button id="search_submit" type="submit"
						class="btn btn-primary btn-sm">
						<span class="glyphicon glyphicon-plus"></span> Ajouter
					</button>
</form>
</div>

<div style="padding:10px">
Supprimer une classe :

 </div>
<div class="form-group">
<form method="POST" action="{% url 'ex_delete_group' exercice_id=exercice.id %}">{% csrf_token %}
					<input id="delete_group_box" type="text" name="delete_group_box"
						class="input-sm form-control" placeholder="Numéro">
					<button id="search_submit" type="submit"
						class="btn btn-warning btn-sm">
						<span class="glyphicon glyphicon-remove"></span> Supprimer
					</button>
</form>
</div>
</div>

{% endif %}
</div>
</div>


<div class="container">
<div class="row">
<div class="col-md-8">


<div class="entete">
<a href="{% url 'detail'  exercice_id=exercice.id %}"> <kbd>#{{ exercice.id }}</kbd> </a>
{% if user == exercice.author %}
<a class="btn btn-default" href="{% url 'post_edit' pk=exercice.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>

<span style="font-size:16px;cursor:pointer" onclick="togNav()"> 
{% if exercice|visible_by_group:'PUBLIC' %}
 <span class="label label-success glyphicon glyphicon-eye-open"> public </span>
{% else %}
 <span class="label label-warning glyphicon glyphicon-eye-open"> limité </span>

{% endif %}</span>
{% else %}
{% if exercice|visible_by_group:'PUBLIC' %}
 <span class="label label-success glyphicon glyphicon-eye-open">  </span>
{% else %}
 <span class="label label-warning glyphicon glyphicon-eye-open">  </span>
{% endif %}
{% endif %}
{% with exercice.id|stringformat:"s" as ex_id %}
{% if 'exobase.see_exercice_'|add:ex_id in perms %}
<button type="button" class="btn  btn-xs" data-toggle="modal" data-target="#myModal">&ltLaTeX&gt</button>

<span class="pull-right">		
 <form method="post" action="{% url 'exercice_add_to_folder' exercice_id=exercice.id %}" style="margin: 0">{% csrf_token %}
    <input  id="add_box" type="number" name="add_ex_box"  placeholder="Add..." style="width: 100px">
    <button id="number_submit" type="submit" >+</button>
</form>
</span>

{% endif %}
{% endwith %}
</div>


<div class="modal fade" id="myModal" role="dialog">
    				<div class="modal-dialog">
    
      				<!-- Modal content-->
      				<div class="modal-content">
        				<div class="modal-header">
          					<button type="button" class="close" data-dismiss="modal">&times;</button>
          					<h4 class="modal-title">{{ exercice.name }}</h4>
        				</div>
        				<div class="modal-body latex">
        				<textarea cols="80" rows="8" onclick="this.focus();this.select()">
          				{{ exercice.enonce_latex }}
          				</textarea>
        				</div>
        				<div class="modal-footer">
          				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        				</div>
      				</div>
      
    				</div>
  				</div>





{% with exercice.id|stringformat:"s" as ex_id %}
{% if 'exobase.see_exercice_'|add:ex_id in perms %}

<div class="">
<div class="title hider"> {{ exercice.name }}   </div>
<div class="wrapper">
<div class="contenthider">

 <div class="description">
<p> {{ exercice.description }} </p>
</div> 
  <div class="metadata"> {% metadata exercice %} </div>
  <ul class="tags">
{% for tag in exercice.tags.all %}
<li><a href="{% url 'exo_list'  tag_slug=tag.slug %}" class="tag"> {{ tag }}</a></li>
{% endfor %}
</ul>
</div>
</div>

 </div>
 

 {% if exercice.enonce_html %}
  <div class="exo">
 
  <div>
                {{ exercice.enonce_html|safe }}
  </div>
  
  </div>
   {% endif %}
 
  {% if exercice.figure %}
    <div class="exo">
  
                 {{ exercice.figure|safe }}
   </div>
 
  {% endif %}
  
  {% if exercice.indication_html %}
  
  <div class="indication">
  <div class="hider">Besoin d'aide ?</div>

<div class="wrapper"> 
<div class="contenthider">
<div class="text">
  {{ exercice.indication_html|safe }}
  </div>
</div>
</div>
</div>
  {% endif %}
  
  <div class="entete"></div>
{% if 'exobase.add_solution' in perms %}
  <a class="btn btn-default pull-left" href="{% url 'exercice_add_solution' exercice_id=exercice.id %}"><span class="glyphicon glyphicon-question-sign">+</span></a>
{% endif %}
 {% block solution %}
 
 {% endblock %}

{% if exercice.solution_set %}
{% for solution in exercice.solution_set.all %}

{% with solution.id|stringformat:"s" as sol_id %}
{% if 'exobase.see_solution_'|add:sol_id in perms %}

<div class="solution">
<button class="accordion title"> Solution #{{ solution.id }} <span class="pull-right">{% metadata solution %}</span> </button>
<div class="panel2"> 

<kbd>#{{ solution.id }}</kbd>
{% if user == solution.author %}
<a class="btn btn-default" href="{% url 'solution_edit' pk=solution.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
<a class="btn btn-default" href="{% url 'solution_delete' pk=solution.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
{% endif %}
<span style="font-size:16px;cursor:pointer" onclick=" "> 
{% if solution|sol_visible_by_group:'PUBLIC' %}
 <span class="label label-success glyphicon glyphicon-eye-open">  </span>
{% else %}
 <span class="label label-warning glyphicon glyphicon-eye-open">  </span>
{% endif %}
</span>


<div class="text">
{{ solution.enonce_html|safe }}
</div>


</div>
</div>
{% endif %}
{% endwith %}

{% endfor %}
{% endif %}

<script>
function openNav() {
    document.getElementById("mySidenav").style.width = "250px";
}

function closeNav() {
    document.getElementById("mySidenav").style.width = "0px";
}

function togNav() {
	  var nav = document.getElementById("mySidenav");
	  if (nav.style.width == '250px') {
	    nav.style.width = '0';
	    nav.style.opacity = 0;
	  } else {
	    nav.style.width = "250px";
	    nav.style.opacity = 1;
	  }
	}
	
function UserSearch() {
    var input, filter, ul, li, a, i;
    input = document.getElementById("myInput");
    filter = input.value.toUpperCase();
    ul = document.getElementById("myUL");
    li = ul.getElementsByTagName("li");
    for (i = 0; i < li.length; i++) {
        a = li[i].getElementsByTagName("a")[0];
        if (a.innerHTML.toUpperCase().indexOf(filter) > -1) {
            li[i].style.display = "";
        } else {
            li[i].style.display = "none";

        }
    }
}

function GroupSearch() {
    var input, filter, ul, li, a, i;
    input = document.getElementById("myInput2");
    filter = input.value.toUpperCase();
    ul = document.getElementById("myUL2");
    li = ul.getElementsByTagName("li");
    for (i = 0; i < li.length; i++) {
        a = li[i].getElementsByTagName("a")[0];
        if (a.innerHTML.toUpperCase().indexOf(filter) > -1) {
            li[i].style.display = "";
        } else {
            li[i].style.display = "none";

        }
    }
}

var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].onclick = function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.maxHeight){
      panel.style.maxHeight = null;
    } else {
      panel.style.maxHeight = panel.scrollHeight + "px";
    } 
  }
}
</script>

{% else %}
<p> Vous n'avez pas l'autorisation pour voir cet exercice </p>
{% endif %}
{% endwith %}



</div>
</div>
</div>


{% endblock %}